name: Publish changes to MkDocs 
# From https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Required for mkdocs-git-revision-date-localized-plugin
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
        # Required install of Python Markdown modules
      - run: pip install mkdocs-material mkdocs-ezlinked-plugin mkdocs-git-revision-date-localized-plugin
      - run: mkdocs gh-deploy --force
